name: Terraform Deployment Workflow

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.6

      - name: Login to Azure using OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set Terraform Azure credentials
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: terraform-plan
        run: |
          terraform plan --var-file=dev_terraform.tfvars -lock=false -out tfplan.out
          terraform show tfplan.out
          terraform show tfplan.out > readable_plan.txt
          
          

      #     ls -la

      # # Convert Terraform Plan to Text
      # - name: Convert Plan to Text
      #   run: |
      #     sleep 30
      #     cat readable_plan.txt

      # - name: Check for Changes
      #   id: check-changes
      #   run: |
      #     changes=$(grep -E '^\s*[~+-]' plan.json | wc -l)
      #     echo "Changes detected: $changes"
      #     # Set an output for the next job to use
      #     if [ "$changes" -gt 0 ]; then
      #       echo "changes=true" >> $GITHUB_ENV
      #       echo "changes=true" >> $GITHUB_OUTPUT
      #     else
      #       echo "changes=false" >> $GITHUB_ENV
      #       echo "changes=false" >> $GITHUB_OUTPUT
      #     fi
      - name: Print changes output for debugging
        run: |
          python changes.py
          cat changes_summary.txt

      # Only send email if there are changes in the Terraform plan
      - name: Send email notification with plan changes
        if: ${{ steps.check-changes.outputs.changes == 'true' }}
        uses: dawidd6/action-send-mail@v2
        with:
          # Mail server settings
          server_address: smtp.gmail.com
          server_port: 465  # SSL port for Gmail
          # User credentials
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          # Email subject
          subject: "Terraform Plan Job: ${{ github.job }} of ${{ github.repository }} has ${{ job.status }}"
          # Email body with the actual Terraform plan changes (added/modified/destroyed resources)
          body: |
            The ${{ github.job }} job in workflow ${{ github.workflow }} of ${{ github.repository }} has ${ job.status }.
            Here are the changes detected in the Terraform plan:
            
            $(cat tfplan.txt)
          # Comma-separated string, send email to
          to: ${{ secrets.RECIPIENT_EMAIL }}
          # From email address (same as the sending email)
          from: ${{ secrets.SMTP_USERNAME }}


  
